### ISSUE TITLE
Throw boxes after death

### ISSUE THREAD

**Issue by kylewr** [Zolo101/5bHTML#10]
## Expected Behavior
When dead, the player should not be able to use the up arrow to throw the box.

## Actual Behavior
If the player dies while near a box, then if the player presses the 'up' arrow key twice, the box will still be thrown as if the player was alive.

## Steps to Reproduce the Problem

  1. Die on top of a box.
  2. Press the up arrow key twice.

## Specifications

  - Version: v2.1 Alpha
  - Browser: Google Chrome 86.0.4240.183 (x64)
  - Operating System: Google Chrome OS 86.0.4240.183 (x64)
*No video, sorry :(*

**Comment by kylewr** [comment]
Also, other boxes that are near the player will move if the up arrow key is pressed repeatedly.

**Comment by Zolo101** [comment]
Fixed in v3 alpha.
