### ISSUE TITLE
Stuck inputs

### ISSUE THREAD

**Issue by Futurama39** [Zolo101/5bHTML#13]
## Expected Behavior
When you hold spacebar you jump and stop jumping when you stop pressing spacebar
## Actual Behavior
When spacebar is pressed for a few seconds, jumping continues after spacebar is no longer pressed

## Specifications
  - Version: alpha 3
  - Browser: Firefox 84.0.1 64-bit
  - Operating System: Win 10 64-bit

**Comment by Futurama39** [comment]
I'm trying to look into this further, right now on level two, and it seems like i can get an input to be "stuck on" despite the button not being pressed, not yet able to reliably reproduce every time.

**Comment by Zolo101** [comment]
I think this has something to do with Firefox tbh... I use Phaser (the game engine for 5bHTML) for keyboard inputs, and if their implementation of inputs don't work, I dont think mine will either, although I haven't actually tried to make my own yet
(btw I was able to reproduce this issue)

**Comment by Zolo101** [comment]
Thank you for the opening the issue, though, I had no idea this happened on Firefox

**Comment by Zolo101** [comment]
Seems to have stopped for now, but still I'm not sure if this was Firefox's fault or 5bHTML's...
