### ISSUE TITLE
boxes imporperly layered

### ISSUE THREAD

**Issue by Futurama39** [Zolo101/5bHTML#14]
## Behavior

![image](https://user-images.githubusercontent.com/12499845/103424122-e5fcb700-4baa-11eb-9a68-6bf6e302c8bf.png)

Box should be rendered behind the menu button

## Specifications

  - Version: alpha 3
  - Browser: Firefox 84.0.1 64-bit
  - Operating System: Win 10 64-bit

**Comment by Futurama39** [comment]
do note that book is also rendered in front of the button

**Comment by Zolo101** [comment]
Fixed

**Comment by Zolo101** [comment]
This seems to only happen when you restart a level

**Comment by Zolo101** [comment]
Fixed in v5 Alpha
