### ISSUE TITLE
No walking animation

### ISSUE THREAD

**Issue by woooowoooo** [Zolo101/5bHTML#18]
## Expected Behavior
There is a walking animation
## Actual Behavior
There is no walking animation

## Steps to Reproduce the Problem

  1. Walk.
  2. Notice how there is no leg movement.
  3. ???
  4. Profit

## Specifications

  - Version: v3 alpha
  - Browser: Firefox 84
  - Operating System: Windows 10

**Comment by Zolo101** [comment]
this is planned, but i'd rather focus on adding levels and gameplay for now

**Comment by Zolo101** [comment]
Added in v5 Alpha
