### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Paramilk** [Zolo101/5bHTML#19]
## Expected Behaviour
Work Alright
## Actual Behaviour
No Story Text, No Music & No Walking Animation

## Steps to Reproduce the Problem

  1.Work On It More
  2.Code More
  3.IDK... Release A Update

## Specifications

  - Version:V.4
  - Browser:Firefox
  - Operating System:Linux(Kubuntu 20.04)

**Comment by Zolo101** [comment]
5bHTML is being worked on daily, you can check progress on the discord. Dialogue, music and animations are planned for future versions

**Comment by Paramilk** [comment]
ok
