### ISSUE TITLE
Saving entities

### ISSUE THREAD

**Issue by woooowoooo** [Zolo101/5bHTML#20]
## Expected Behavior
Test-running the level is not required to save entities.
## Actual Behavior
Entity changes are not saved unless before a test-run, even if you hit the Save button.
## Steps to Reproduce the Problem

  1. Go to Level Editor and create a level.
  2. Do at least one of the following:
    a. Add a box.
    b. Move existing entities around.
    c. Delete some.
  3. Save the level. Do not run it from the editor.
  4. Exit the editor.
  5. Play the level. Notice how your changes were not saved.

## Specifications

  - Version: dev-21w15b
  - Browser: Firefox 88.0b9
  - Operating System: Linux Mint 20.1 x86_64

**Comment by Zolo101** [comment]
Fixed in 21w15c.
