### ISSUE TITLE
Leftover entites in new level

### ISSUE THREAD

**Issue by woooowoooo** [Zolo101/5bHTML#21]
## Expected Behavior
When you create a new level, the level editor is clear.
## Actual Behavior
Although the blocks are clear, entities from the previous level are still present.
## Steps to Reproduce the Problem

  1. Finish creating a level in level editor. This level must include at least one entity.
  2. Start creating a new level by clicking the "New Levelpack" button.
  3. Notice how the entities roll over.

## Specifications

  - Version: dev-21w15b
  - Browser: Firefox 88.0b9
  - Operating System: Linux Mint 20.1 x86_64

**Comment by Zolo101** [comment]
Fixed in 21w15c.
