### ISSUE TITLE
Jiggly positioning on entities

### ISSUE THREAD

**Issue by woooowoooo** [Zolo101/5bHTML#23]
## Expected Behavior
When you stand on a box, you don't jiggle up and down.
## Actual Behavior
You end up jiggling up and down when standing on a box.
## Steps to Reproduce the Problem

  1. Play a level with boxes in it.
  2. Jump onto one. Notice the jiggle.

## Specifications

  - Version: dev-21w15b
  - Browser: Firefox 88.0b9
  - Operating System: Linux Mint 20.1 x86_64

**Comment by Zolo101** [comment]
Explaination of why this happens is in #16

**Comment by Futurama39** [comment]
I'm for closing this in favour of #16 as it's the same cause essentially
