### ISSUE TITLE
Cloning when renaming levels

### ISSUE THREAD

**Issue by woooowoooo** [Zolo101/5bHTML#24]
## Expected Behavior
Renaming a level doesn't duplicate the level.
## Actual Behavior
Renaming a level duplicates the level.
## Steps to Reproduce the Problem

  1. Create a level.
  2. Enter the "Rename" screen by clicking the Rename button at the top-right.
  3. Rename the title of that level.
    a. OPTIONAL: Add a description.
  4. Exit the screen. The level has duplicated. If you added a description, this is put into both copies of the level.

## Specifications

  - Version: dev-21w15b
  - Browser: Firefox 88.0b9
  - Operating System: Linux Mint 20.1 x86_64

**Comment by Zolo101** [comment]
This seems to only happen with changing titles. The duplicated level doesn't actually exist, and is just a reference to the original one, so there's no danger in using it. It also goes away after a refresh.

**Comment by Zolo101** [comment]
Fixed in v4 alpha.
