### ISSUE TITLE
Level editor not responsive to browser zoom

### ISSUE THREAD

**Issue by Futurama39** [Zolo101/5bHTML#26]
When the zoom level is changed while in the level editor, the editor does not update and can either obscure stuff out of view or make a big black bar on the right side of the screen, pictured below:
![image](https://user-images.githubusercontent.com/12499845/124398949-bb85e500-dd18-11eb-8ce4-3b8ce3ffbe1c.png)

## Specifications

  - Version: v4 alpha
  - Browser: Firefox  89.0.2 (64-bit)
  - Operating System: Win 10 64-bit

**Comment by Zolo101** [comment]
Also happens when maximizing the window (anything that isnt resizing manually by the mouse)

**Comment by Zolo101** [comment]
Fixed in v4.1 Alpha
