### ISSUE TITLE
You can pick boxes up from behind you, but only on the left side of it.

### ISSUE THREAD

**Issue by SpencilBoy** [Zolo101/5bHTML#38]
## Expected Behavior
When you are behind a box on the left side, you will not be able to pick it up.
## Actual Behavior
When you are behind a box on the left side, you actually **CAN** pick it up.

## Steps to Reproduce the Problem

  1. Make a level with a box
  2. Go to the box and make it so you're facing away from it on the left side
  3. Press the Up key and see the box in your hands

## Specifications

  - Version: v5
  - Browser: Google Chrome 90.2.4515.107
  - Operating System: Windows 8.1
<img width="194" alt="book next to box" src="https://user-images.githubusercontent.com/88171247/127942262-d1fabcb7-31ca-4b47-89d0-8ab889bc972d.PNG">
<img width="209" alt="book now holding box" src="https://user-images.githubusercontent.com/88171247/127942366-02bf0575-1e0b-45a5-9eb2-9e36a0d85644.PNG">

**Comment by SpencilBoy** [comment]
This is most likely just a hitbox issue, probably the game thinking that since book's asset is faced towards the box, it has the same grab hitbox as if book **WAS** facing towards the box.

**Comment by Zolo101** [comment]
Fixed in v6 Alpha

**Comment by SpencilBoy** [comment]
nice
