### ISSUE TITLE
Level names don't get replaced after beating a level (I can't think of a shorter title)

### ISSUE THREAD

**Issue by meisels** [Zolo101/5bHTML#8]
## Expected Behavior
The level name changes between levels.

## Actual Behavior
The new level name appears OVER the old one.

## Steps to Reproduce the Problem

  1. Beat any level

## Specifications

  - Version: 2.1 Alpha
  - Browser: Chrome v85.0.4183.121 (x64)
  - Operating System: Windows 8.1 (x64)

**Comment by kylewr** [comment]
The same thing happens with me.
