### ISSUE TITLE
Box getting stuck in spikes & text glitch

### ISSUE THREAD

**Issue by kylewr** [Zolo101/5bHTML#9]
## Expected Behavior
1. Not get stuck in spikes and just bounce off of them. (Level 005 I think)
2. Text displays the level properly

## Actual Behavior
1. Spikes "catch" the box and it gets stuck
2. Text is broken and just overlays the previous level text.

### Box spike issue:
  1. Get the box and go to the first spikes
  2. Jump and throw the box at the right time
  3. It gets stuck
### Text issue:
1. Progress through the levels? I'm not really sure on this one.

## Specifications

  - Version: v2.1 Alpha
  - Browser: Chrome 86 (64-Bit)
  - Operating System: Chrome OS

## IMAGE:
![zolo_issue](https://user-images.githubusercontent.com/24662892/99327023-05cc5b80-2847-11eb-8723-3a51a12de74d.png)

**Comment by Zolo101** [comment]
The text glitch has been fixed in the dev build but hasn't been released yet on a stable build

**Comment by Zolo101** [comment]
Fixed in v3 alpha.
